### ISSUE TITLE
Site Down: Issue with the DNS of Yogurl.io

### ISSUE THREAD

**Issue by Ma5onic** [720kb/yogurl#5]
I tried visiting yogurl.io but the site couldn't be reached. Here is what I found:
-Whois lookup shows that the domain is not expired.
-The website did not respond to nslookups, pings or traceroutes. 
-It seems like the DNS is not able to resolve any the requests.
_______________________________________________________________________________________________________________

These are the results of the test that I performed:

C:\Users\Home>nslookup Yogurl.io
Server:  UnKnown
Address:  192.168.0.1

*** UnKnown can't find Yogurl.io: Non-existent domain

C:\Users\Home>nslookup debug Yogurl.io
*** Can't find server address for 'Yogurl.io':
Server:  UnKnown
Address:  192.168.0.1

*** UnKnown can't find debug: Non-existent domain

C:\Users\Home>ping Yogurl.io
Ping request could not find host Yogurl.io. Please check the name and try again.

C:\Users\Home>tracert Yogurl.io
Unable to resolve target system name Yogurl.io.

**Comment by 45kb** [comment]
Hi should be up in days
